const creativePrompts = {
    hook: [
        "Smack them with a wild ‘what if’ they can’t shake!",
        "Tease a secret they’ll beg to know.",
        "Hit them with a stat that stops their scroll.",
        "Ask a question that haunts their dreams.",
        "Drop a truth bomb they can’t unhear.",
        "Paint a picture too vivid to ignore.",
        "Reveal a twist they’ll never see coming.",
        "Call out their biggest fear, no filter.",
        "Start with a line that burns their brain.",
        "Throw a curveball that flips their world.",
        "Dangle a promise they can’t resist.",
        "Expose a lie they’ve lived too long.",
        "Kick off with a dare they can’t refuse.",
        "Show a glimpse of their hidden potential.",
        "Rip the mask off their daily grind.",
        "Spark a ‘holy shit’ moment fast.",
        "Lay out a paradox they can’t solve.",
        "Hit them with a quote that stings.",
        "Tease a hack they’ll wish they knew.",
        "Open with a confession that shocks.",
        "Bait them with a forbidden truth.",
        "Drop a cliffhanger they’ll chase all day.",
        "Smash a myth they cling to tight.",
        "Ask what they’d kill to know.",
        "Start with a flop they’ll relate to.",
        "Unveil a trend they’re blind to.",
        "Punch them with a raw reality check.",
        "Tease a payoff too good to skip.",
        "Reveal a flaw they can’t deny.",
        "Kick it with a ‘you’re doing this wrong.’",
        "Paint their future in neon lights.",
        "Drop a riddle they’ll itch to crack.",
        "Call their bluff with zero chill.",
        "Start with a whisper that screams loud.",
        "Expose a scam they’ve fallen for.",
        "Hit them with a ‘bet you didn’t know.’",
        "Tease a win they can taste now.",
        "Open with a scar they’ll recognize.",
        "Ask a ‘what if’ that rewires them.",
        "Drop a fact that flips their script.",
        "Show a shortcut they’ve walked past.",
        "Rip into a habit they defend.",
        "Start with a bang they can’t mute.",
        "Reveal a gap they’ve ignored too long.",
        "Hit them with a twist that sticks.",
        "Tease a truth they’ve dodged forever.",
        "Kick off with a slap of clarity.",
        "Paint a ‘what could be’ they crave.",
        "Drop a line that cuts like glass.",
        "Call out a dream they’ve buried deep.",
        "Start with a glitch they can’t unsee.",
        "Expose a trap they’re stuck in.",
        "Hit them with a spark that burns.",
        "Tease a fix they’ll steal fast.",
        "Open with a jolt they’ll feel.",
        "Ask a question that flips their lens.",
        "Drop a hook that drags them in.",
        "Show a flaw they’ve dressed as strength.",
        "Rip open a wound they hide.",
        "Start with a truth they’ve run from.",
        "Reveal a hack that flips the game.",
        "Hit them with a ‘this changes everything.’",
        "Tease a peek they can’t unpeek.",
        "Kick off with a punch they’ll cheer.",
        "Paint a scene that grips their gut.",
        "Drop a stat that shatters their calm.",
        "Call out a lie they’ve bought.",
        "Start with a ‘you’re not alone’ vibe.",
        "Expose a myth that’s held them back.",
        "Hit them with a dare that bites.",
        "Tease a truth that’s raw as hell.",
        "Open with a twist that turns heads.",
        "Ask a ‘why not’ they can’t dodge.",
        "Drop a bomb that wakes them up.",
        "Show a path they’ve never dared.",
        "Rip into a fear they mask.",
        "Start with a win they can smell.",
        "Reveal a snag they’ve tripped on.",
        "Hit them with a line that haunts.",
        "Tease a shift they’ll chase down.",
        "Kick off with a spark that sticks.",
        "Paint a fail they’ll nod to.",
        "Drop a truth they can’t shake off.",
        "Call out a rut they’re blind to.",
        "Start with a hook that hooks hard.",
        "Expose a flaw they’ve glossed over.",
        "Hit them with a ‘you’ve been lied to.’",
        "Tease a win that’s one step away.",
        "Open with a sting they’ll respect.",
        "Ask a question that breaks their mold.",
        "Drop a fact that flips their day.",
        "Show a trick they’ll swipe tonight.",
        "Rip open a scam they trust.",
        "Start with a bang they’ll replay.",
        "Reveal a truth that cuts deep.",
        "Hit them with a twist they crave.",
        "Tease a hack that’s pure gold.",
        "Kick off with a jolt that lands."
    ],
    story: [
        "Tell the day you crashed and burned.",
        "Spill a moment you’d rather forget.",
        "Share the fight you didn’t win.",
        "Relive the time you bet it all.",
        "Paint the scene you barely survived.",
        "Reveal the choice that broke you.",
        "Tell the night you couldn’t sleep.",
        "Spill the mistake that haunts you.",
        "Share the loss that shaped you.",
        "Relive the call that changed it.",
        "Paint the fail you laugh at now.",
        "Reveal the risk that went bust.",
        "Tell the time you got it wrong.",
        "Spill the truth you hid back then.",
        "Share the grind that wore you thin.",
        "Relive the day you walked away.",
        "Paint the mess you crawled through.",
        "Reveal the doubt that ate you up.",
        "Tell the win you almost missed.",
        "Spill the fear you faced down.",
        "Share the flop that fueled you.",
        "Relive the moment you broke free.",
        "Paint the scar you earned hard.",
        "Reveal the fall that lifted you.",
        "Tell the day you said ‘enough.’",
        "Spill the secret you kept too long.",
        "Share the blow you didn’t dodge.",
        "Relive the hustle that paid off.",
        "Paint the chaos you turned around.",
        "Reveal the pivot that saved you.",
        "Tell the time you burned out.",
        "Spill the lesson you bled for.",
        "Share the dream you let die.",
        "Relive the clash that woke you.",
        "Paint the rut you clawed out.",
        "Reveal the gamble that tanked fast.",
        "Tell the night you found your why.",
        "Spill the truth you choked on.",
        "Share the hit you didn’t see.",
        "Relive the spark that lit you.",
        "Paint the grind you beat down.",
        "Reveal the miss that made you.",
        "Tell the day you flipped it.",
        "Spill the doubt you drowned out.",
        "Share the leap that landed rough.",
        "Relive the win you stole back.",
        "Paint the wall you smashed through.",
        "Reveal the slip you turned gold.",
        "Tell the time you stood alone.",
        "Spill the fail you owned up.",
        "Share the scar you wear proud.",
        "Relive the choice you almost skipped.",
        "Paint the dark you stumbled through.",
        "Reveal the twist that pulled you.",
        "Tell the day you rewrote rules.",
        "Spill the fear you laughed off.",
        "Share the bust that built you.",
        "Relive the moment you snapped back.",
        "Paint the crash you rose from.",
        "Reveal the gut punch you took.",
        "Tell the night you saw clear.",
        "Spill the mistake you milked dry.",
        "Share the loss you flipped fast.",
        "Relive the fight you barely won.",
        "Paint the hole you climbed out.",
        "Reveal the risk that reshaped you.",
        "Tell the time you broke loose.",
        "Spill the truth you fought for.",
        "Share the flop you turned tight.",
        "Relive the day you found grit.",
        "Paint the mess you made right.",
        "Reveal the fall you caught quick.",
        "Tell the win you scratched out.",
        "Spill the doubt you burned up.",
        "Share the hit that forged you.",
        "Relive the pivot you nailed.",
        "Paint the grind you outran.",
        "Reveal the slip you spun gold.",
        "Tell the day you said ‘screw it.’",
        "Spill the fear you tore down.",
        "Share the bust you bounced from.",
        "Relive the spark you chased hard.",
        "Paint the scar you turned art.",
        "Reveal the miss you made big.",
        "Tell the time you stood tall.",
        "Spill the fail you flipped quick.",
        "Share the loss you laughed at.",
        "Relive the clash you owned up.",
        "Paint the rut you broke free.",
        "Reveal the gamble you won late.",
        "Tell the night you rebuilt you.",
        "Spill the truth you dug up.",
        "Share the blow you rolled with.",
        "Relive the hustle you crushed.",
        "Paint the chaos you tamed fast.",
        "Reveal the pivot you pulled off.",
        "Tell the day you burned bright.",
        "Spill the lesson you carved out.",
        "Share the dream you clawed back."
    ],
    lesson: [
        "Strip it to a truth they can’t dodge.",
        "Turn their ‘duh’ into a ‘whoa.’",
        "Drop a gem they’ll carry forever.",
        "Flip a lie they’ve swallowed whole.",
        "Boil it down to one sharp point.",
        "Reveal the thread that ties it.",
        "Hit them with a ‘now I get it.’",
        "Smash a belief they’ve clung to.",
        "Cut the fat, leave the meat.",
        "Show the root they’ve never dug.",
        "Drop a truth that stings a bit.",
        "Flip their lens with one twist.",
        "Bare a lesson they can’t unlearn.",
        "Point to the gold they’ve missed.",
        "Strip away the noise they trust.",
        "Reveal a shift they’ll feel deep.",
        "Hit them with a raw ‘aha.’",
        "Smash the crutch they lean on.",
        "Cut to a truth that bites.",
        "Show the flaw they’ve dressed up.",
        "Drop a line that sticks hard.",
        "Flip a fear into a win.",
        "Bare a nugget they’ll steal fast.",
        "Point to a lie they live.",
        "Strip it to a spark that burns.",
        "Reveal the catch they’ve ignored.",
        "Hit them with a truth that lands.",
        "Smash a myth they’ve built on.",
        "Cut the fluff, serve the core.",
        "Show the gap they’ve danced around.",
        "Drop a lesson that cuts clean.",
        "Flip a doubt into a dare.",
        "Bare a truth they can’t shake.",
        "Point to the trap they’re in.",
        "Strip away a shield they hide.",
        "Reveal a twist that wakes them.",
        "Hit them with a ‘damn, that’s it.’",
        "Smash a rule they’ve followed blind.",
        "Cut to a gem that glows.",
        "Show the snag they’ve tripped over.",
        "Drop a truth that flips fast.",
        "Flip a fail into a gift.",
        "Bare a lesson they’ll tattoo on.",
        "Point to a flaw they’ve masked.",
        "Strip it to a line that haunts.",
        "Reveal the root they’ve skipped.",
        "Hit them with a spark that sticks.",
        "Smash a wall they’ve built high.",
        "Cut the haze, leave the light.",
        "Show the lie they’ve bought cheap.",
        "Drop a truth that turns heads.",
        "Flip a rut into a road.",
        "Bare a gem they can’t drop.",
        "Point to the miss they mourn.",
        "Strip away a crutch they clutch.",
        "Reveal a truth that stabs deep.",
        "Hit them with a ‘holy crap.’",
        "Smash a habit they defend.",
        "Cut to a lesson that sings.",
        "Show the flaw they’ve glossed up.",
        "Drop a line that burns bright.",
        "Flip a fear into a fire.",
        "Bare a truth they’ll chase down.",
        "Point to a trap they’ve set.",
        "Strip it to a jolt that jars.",
        "Reveal the shift they’ve dodged.",
        "Hit them with a truth that grips.",
        "Smash a myth they’ve slept on.",
        "Cut the noise, serve the punch.",
        "Show the gap they’ve run from.",
        "Drop a lesson that lands hard.",
        "Flip a doubt into a drive.",
        "Bare a gem they’ll grab quick.",
        "Point to the lie they lean.",
        "Strip away a veil they wear.",
        "Reveal a twist that turns them.",
        "Hit them with a ‘now I see.’",
        "Smash a rule they’ve bent for.",
        "Cut to a truth that shines.",
        "Show the snag they’ve skipped past.",
        "Drop a truth that sticks tight.",
        "Flip a fail into a flame.",
        "Bare a lesson they can’t skip.",
        "Point to a flaw they’ve hid.",
        "Strip it to a spark that lasts.",
        "Reveal the catch they’ve missed.",
        "Hit them with a line that cuts.",
        "Smash a belief they’ve held dear.",
        "Cut the fluff, leave the edge.",
        "Show the root they’ve walked by.",
        "Drop a gem that bites back.",
        "Flip a fear into a fight.",
        "Bare a truth they’ll feel fast.",
        "Point to a trap they’ve built.",
        "Strip away a lie they love.",
        "Reveal a shift that shocks them.",
        "Hit them with a truth that stays.",
        "Smash a myth they’ve stood on."
    ],
    action: [
        "Give them a 5-minute win they can try.",
        "Make it so simple they can’t say no.",
        "Point to a switch they can flip now.",
        "Drop a hack they’ll use by dawn.",
        "Tell them one move to crush it.",
        "Show a step that’s pure fire.",
        "Hand them a trick they’ll swipe fast.",
        "Cut a task they can nail today.",
        "Reveal a tweak that doubles down.",
        "Push a button they can hit quick.",
        "Give them a play they can run.",
        "Make it a no-brainer they’ll grab.",
        "Point to a fix they can test.",
        "Drop a tip that’s instant gold.",
        "Tell them a move that sparks joy.",
        "Show a hack that’s too damn easy.",
        "Hand them a step that sticks.",
        "Cut a win they can claim now.",
        "Reveal a twist they can turn.",
        "Push a lever they can pull fast.",
        "Give them a jolt they can feel.",
        "Make it a snap they can’t miss.",
        "Point to a trick they’ll love.",
        "Drop a play that pays off quick.",
        "Tell them a tweak that shines.",
        "Show a step that’s pure grit.",
        "Hand them a fix that flies.",
        "Cut a task they can smash.",
        "Reveal a hack that hits hard.",
        "Push a move they can make.",
        "Give them a win that’s one click.",
        "Make it a step they’ll jump on.",
        "Point to a shift they can own.",
        "Drop a tip that’s pure heat.",
        "Tell them a play that pops.",
        "Show a trick that turns heads.",
        "Hand them a tweak that works.",
        "Cut a win they can snag.",
        "Reveal a step that’s too slick.",
        "Push a fix they can grab.",
        "Give them a hack that hums.",
        "Make it a move they can’t skip.",
        "Point to a play that bites.",
        "Drop a tweak that burns bright.",
        "Tell them a step that lands.",
        "Show a fix that’s pure rush.",
        "Hand them a tip that grips.",
        "Cut a task they can crush.",
        "Reveal a trick that flips it.",
        "Push a win they can taste.",
        "Give them a step that stings.",
        "Make it a hack they’ll chase.",
        "Point to a fix that sparks.",
        "Drop a play that’s pure edge.",
        "Tell them a tweak that cuts.",
        "Show a move that’s too hot.",
        "Hand them a win that sings.",
        "Cut a step they can rip.",
        "Reveal a hack that wakes them.",
        "Push a tip they can steal.",
        "Give them a play that shocks.",
        "Make it a fix they’ll run.",
        "Point to a tweak that bites.",
        "Drop a step that’s pure gold.",
        "Tell them a trick that sticks.",
        "Show a win that’s too fast.",
        "Hand them a move that glows.",
        "Cut a hack they can grab.",
        "Reveal a play that turns it.",
        "Push a step they can nail.",
        "Give them a tip that’s raw.",
        "Make it a win they’ll feel.",
        "Point to a fix that flies.",
        "Drop a tweak that’s pure guts.",
        "Tell them a play that grips.",
        "Show a step that burns fast.",
        "Hand them a hack that lands.",
        "Cut a move they can snap.",
        "Reveal a tip that cuts deep.",
        "Push a win they can claim.",
        "Give them a trick that pops.",
        "Make it a fix they’ll swipe.",
        "Point to a step that hums.",
        "Drop a play that’s too sharp.",
        "Tell them a tweak that stuns.",
        "Show a hack that’s pure fire.",
        "Hand them a win that bites.",
        "Cut a step they can own.",
        "Reveal a move that shines.",
        "Push a tip that turns heads.",
        "Give them a play that’s tight.",
        "Make it a hack they can’t drop.",
        "Point to a fix that sparks joy.",
        "Drop a step that’s pure rush.",
        "Tell them a win that sticks.",
        "Show a tweak that hits home.",
        "Hand them a trick that flies.",
        "Cut a play they can crush."
    ],
    problem: [
        "Name the ache they can’t shake off.",
        "Point to a rut they’re stuck in.",
        "Call out a snag they’ve hit hard.",
        "Reveal the mess they’re dodging.",
        "Highlight a fight they’re losing.",
        "Expose a gap they can’t fill.",
        "Show the grind that’s grinding them.",
        "Pin down a pain they hide.",
        "Drop a flaw they trip over.",
        "Tease a struggle they’ve muted.",
        "Hit the block they can’t bust.",
        "Unveil a snag that stings.",
        "Name a trap they’re caught in.",
        "Point to a wall they’ve slammed.",
        "Call out a fear they bury.",
        "Reveal a hole they’re sinking.",
        "Show a hitch they can’t fix.",
        "Pin a doubt they wrestle.",
        "Drop a glitch they ignore.",
        "Tease a jam they’re jammed in.",
        "Hit a snag that’s pure hell.",
        "Unveil a rut that bites.",
        "Name a fight they’re faking.",
        "Point to a mess they dread.",
        "Call out a flaw that burns.",
        "Reveal a grind they hate.",
        "Show a trap that’s tight.",
        "Pin down a fear that grips.",
        "Drop a pain they duck.",
        "Tease a block they dodge.",
        "Hit a hole they’ve dug.",
        "Unveil a snag they loathe.",
        "Name a rut that’s raw.",
        "Point to a fight they flee.",
        "Call out a hitch that haunts.",
        "Reveal a mess that mocks.",
        "Show a flaw they flinch.",
        "Pin a grind that grates.",
        "Drop a trap they’ve tripped.",
        "Tease a doubt that lingers.",
        "Hit a pain that’s pure fire.",
        "Unveil a block that blinds.",
        "Name a snag they’re scared.",
        "Point to a rut that rules.",
        "Call out a fear that freezes.",
        "Reveal a hole that hurts.",
        "Show a fight they fake.",
        "Pin down a mess that mocks.",
        "Drop a glitch that gnaws.",
        "Tease a trap they’re trapped.",
        "Hit a flaw that’s fierce.",
        "Unveil a grind that grips.",
        "Name a hitch that hums.",
        "Point to a pain they push.",
        "Call out a block that breaks.",
        "Reveal a snag that sneaks.",
        "Show a rut that roars.",
        "Pin a doubt that digs.",
        "Drop a fight they fold.",
        "Tease a mess that melts.",
        "Hit a trap that twists.",
        "Unveil a flaw that flares.",
        "Name a grind that groans.",
        "Point to a fear that fades.",
        "Call out a hole that hides.",
        "Reveal a hitch that holds.",
        "Show a pain that pulls.",
        "Pin down a snag that sticks.",
        "Drop a block that bends.",
        "Tease a rut that rages.",
        "Hit a fight that falls.",
        "Unveil a mess that mutes.",
        "Name a flaw that fries.",
        "Point to a trap that ties.",
        "Call out a doubt that drifts.",
        "Reveal a grind that guts.",
        "Show a hitch that hangs.",
        "Pin a pain that pounds.",
        "Drop a snag that spins.",
        "Tease a block that binds.",
        "Hit a rut that runs.",
        "Unveil a fear that fights.",
        "Name a hole that howls.",
        "Point to a mess that moves.",
        "Call out a flaw that floods.",
        "Reveal a trap that turns.",
        "Show a fight that fails.",
        "Pin down a grind that glows.",
        "Drop a hitch that hooks.",
        "Tease a pain that peaks.",
        "Hit a snag that sinks.",
        "Unveil a block that blares.",
        "Name a rut that rips.",
        "Point to a doubt that drops.",
        "Call out a mess that mends.",
        "Reveal a flaw that flows.",
        "Show a trap that traps.",
        "Pin a fight that fizzles.",
        "Drop a grind that grows.",
        "Tease a hitch that hurts."
    ],
    agitation: [
        "Twist the knife they’re bleeding from.",
        "Pile on the chaos they can’t stand.",
        "Show the hell they’re headed for.",
        "Rub salt in their open wound.",
        "Crank up the heat they feel.",
        "Paint the doom they’re dodging.",
        "Amp the stakes they’re scared of.",
        "Stir the pot they’ve ignored.",
        "Push the panic they’re pushing down.",
        "Tease the crash they can’t stop.",
        "Turn up the noise they hate.",
        "Lay bare the mess they’ve made.",
        "Double down on their dread.",
        "Flaunt the fall they’re flirting.",
        "Boost the burn they’re burying.",
        "Sketch the storm they’re stuck in.",
        "Raise the red they’re running.",
        "Prod the pain they pretend.",
        "Fan the flames they fear.",
        "Hint at havoc they’re hiding.",
        "Crush the calm they cling to.",
        "Expose the edge they’re on.",
        "Dial up the dark they dread.",
        "Taunt the trap they’re tripping.",
        "Sharpen the sting they shun.",
        "Draw out the doubt they duck.",
        "Rattle the cage they’re caught.",
        "Pump the pressure they’re pressed.",
        "Unleash the unrest they’ve unleashed.",
        "Mock the mask they’re making.",
        "Spike the stress they’re skipping.",
        "Bare the break they’re breaking.",
        "Lift the lid they’ve locked.",
        "Twist the truth they twist.",
        "Blast the block they’re blind.",
        "Fuel the fire they flee.",
        "Shake the shame they shove.",
        "Rip the rug they’re rooted.",
        "Hike the hurt they hush.",
        "Peel the peace they paint.",
        "Stoke the storm they stall.",
        "Grind the grit they groan.",
        "Flip the fear they fake.",
        "Crack the cool they crave.",
        "Boost the bust they bury.",
        "Wrench the wreck they’re wrecked.",
        "Turn the tide they turn.",
        "Fry the front they fight.",
        "Ramp the rage they run.",
        "Slam the slip they slide.",
        "Blow the boil they’ve built.",
        "Churn the chaos they chase.",
        "Spike the snag they snag.",
        "Tear the thread they thread.",
        "Roar the rut they rue.",
        "Whip the wind they wish.",
        "Burn the bridge they built.",
        "Crush the crutch they clutch.",
        "Raise the wreck they’ve wrought.",
        "Scream the silence they seek.",
        "Jolt the jam they’re jammed.",
        "Fling the flaw they flinch.",
        "Grate the grind they grip.",
        "Snap the slack they slack.",
        "Push the pit they’ve pitched.",
        "Rend the rest they’ve robbed.",
        "Drill the dread they dodge.",
        "Blare the bust they bust.",
        "Tug the trap they’ve tied.",
        "Scorch the shield they show.",
        "Shake the shit they shove.",
        "Break the brace they brace.",
        "Singe the skin they shed.",
        "Rush the rut they rush.",
        "Crank the crash they crawl.",
        "Rip the rope they’re roped.",
        "Freak the fix they fake.",
        "Howl the hole they hide.",
        "Thrash the calm they claim.",
        "Wring the wrong they wrong.",
        "Blast the block they bear.",
        "Stab the still they steal.",
        "Fume the fight they flail.",
        "Smash the safe they seek.",
        "Rile the raw they run.",
        "Yank the yoke they yoke.",
        "Clash the cool they cling.",
        "Spill the spill they spin.",
        "Rage the rest they rob.",
        "Jerk the jam they jar.",
        "Torch the truce they trick.",
        "Wail the wall they wall.",
        "Thump the thump they thump.",
        "Frazzle the front they front.",
        "Shred the shield they shape.",
        "Roil the rut they roll.",
        "Slam the snag they snag.",
        "Bust the bluff they bluff.",
        "Whack the wreck they wreck.",
        "Fry the fear they fry."
    ],
    solution: [
        "Drop a fix that flips the script.",
        "Hand them a key they can turn.",
        "Give a step that’s stupid simple.",
        "Reveal a hack they’ll hug tight.",
        "Show a path that’s pure gold.",
        "Offer a trick that ticks fast.",
        "Point to a win they’ll grab.",
        "Tease a tool they’ve got handy.",
        "Cut a cure that clicks now.",
        "Serve a spark that saves them.",
        "Drop a play that pays off.",
        "Hand them a move that melts.",
        "Give a twist that triumphs.",
        "Reveal a gem that gleams.",
        "Show a fix that’s fierce fun.",
        "Offer a step that stuns.",
        "Point to a hack that heals.",
        "Tease a win that wows.",
        "Cut a trick that’s too easy.",
        "Serve a key that kicks in.",
        "Drop a path that pulls through.",
        "Hand them a fix that flies.",
        "Give a tool that turns it.",
        "Reveal a play that pops off.",
        "Show a cure that cuts deep.",
        "Offer a hack that hooks.",
        "Point to a step that sings.",
        "Tease a spark that shifts.",
        "Cut a win that’s wild free.",
        "Serve a move that mends fast.",
        "Drop a trick that’s pure heat.",
        "Hand them a gem that grips.",
        "Give a fix that’s fresh fire.",
        "Reveal a tool that triumphs.",
        "Show a path that’s pure rush.",
        "Offer a step that sticks.",
        "Point to a play that peaks.",
        "Tease a cure that clicks.",
        "Cut a hack that’s all guts.",
        "Serve a win that works now.",
        "Drop a key that kills doubt.",
        "Hand them a twist that thrives.",
        "Give a fix that’s fast gold.",
        "Reveal a move that melts stress.",
        "Show a trick that’s too good.",
        "Offer a path that pulls up.",
        "Point to a gem that glows.",
        "Tease a step that snaps back.",
        "Cut a tool that turns tides.",
        "Serve a hack that hums right.",
        "Drop a play that’s pure spark.",
        "Hand them a cure that cuts through.",
        "Give a win that’s wicked sharp.",
        "Reveal a fix that fires up.",
        "Show a key that kicks ass.",
        "Offer a trick that takes off.",
        "Point to a move that mends quick.",
        "Tease a path that’s pure grit.",
        "Cut a step that’s stone solid.",
        "Serve a gem that gets it.",
        "Drop a hack that hits home.",
        "Hand them a tool that twists fate.",
        "Give a fix that flies high.",
        "Reveal a win that wows them.",
        "Show a play that pulls free.",
        "Offer a cure that crushes it.",
        "Point to a trick that triumphs.",
        "Tease a step that’s too slick.",
        "Cut a key that kills chaos.",
        "Serve a move that makes peace.",
        "Drop a path that’s pure edge.",
        "Hand them a fix that flips fast.",
        "Give a gem that grabs hold.",
        "Reveal a hack that heals deep.",
        "Show a win that’s wild win.",
        "Offer a tool that turns heads.",
        "Point to a play that pops loud.",
        "Tease a cure that cuts clean.",
        "Cut a step that’s surefire.",
        "Serve a trick that sings sweet.",
        "Drop a fix that’s full force.",
        "Hand them a key that kicks off.",
        "Give a move that mows down.",
        "Reveal a path that pulls strong.",
        "Show a hack that hooks tight.",
        "Offer a win that winks back.",
        "Point to a gem that glows bright.",
        "Tease a tool that takes over.",
        "Cut a play that’s pure punch.",
        "Serve a step that slams shut.",
        "Drop a cure that’s crazy good.",
        "Hand them a fix that flies free.",
        "Give a trick that turns gold.",
        "Reveal a move that melts fear.",
        "Show a key that kills it.",
        "Offer a path that peaks high.",
        "Point to a hack that hums loud.",
        "Tease a win that wipes out.",
        "Cut a gem that gets them.",
        "Serve a fix that’s flat-out."
    ],
    question: [
        "What’s the one thing they can’t crack?",
        "Why do they keep tripping here?",
        "Ever wonder what’s holding them back?",
        "How long till they break this?",
        "What if they flipped it now?",
        "Who’s got the guts to try?",
        "Why’s this still a damn mess?",
        "What’s the catch they can’t see?",
        "How do they dodge this trap?",
        "Ever think they’re missing this?",
        "What’s the fear they won’t name?",
        "Why’s it always the same rut?",
        "How come they’re stuck again?",
        "What if they ditched the noise?",
        "Who’s brave enough to shift?",
        "Why’s this snag still alive?",
        "What’s the truth they’re ducking?",
        "How long till they wake up?",
        "Ever ask why it’s so hard?",
        "What’s the block they won’t bust?",
        "Why do they fake this fight?",
        "How’s this still screwing them?",
        "What if they broke it today?",
        "Who’s got the spark to start?",
        "Why’s the fix so damn far?",
        "What’s the lie they’ve lived?",
        "How come they can’t let go?",
        "Ever wonder what’s beneath this?",
        "What’s the doubt they’re dodging?",
        "Why’s this grind still grinding?",
        "How long till they grab it?",
        "What if they flipped the switch?",
        "Who’s bold enough to jump?",
        "Why’s this mess their master?",
        "What’s the snag they’re scared?",
        "How do they miss this gem?",
        "Ever think they’re too close?",
        "What’s the trap they’re trapped?",
        "Why’s it always this chaos?",
        "How come they won’t budge?",
        "What if they cut the crap?",
        "Who’s got the balls to break?",
        "Why’s this hole still open?",
        "What’s the truth they twist?",
        "How long till they see it?",
        "Ever ask what’s really up?",
        "What’s the rut they run?",
        "Why do they duck this fix?",
        "How’s this fight still fighting?",
        "What if they owned it now?",
        "Who’s tough enough to turn?",
        "Why’s this pain their pal?",
        "What’s the block they bury?",
        "How come they’re blind to this?",
        "Ever wonder why they stall?",
        "What’s the snag they skip?",
        "Why’s this grind their god?",
        "How long till they snap free?",
        "What if they ditched the doubt?",
        "Who’s got the grit to go?",
        "Why’s this trap still tight?",
        "What’s the lie they lean?",
        "How do they miss the mark?",
        "Ever think they’re too stuck?",
        "What’s the fear they feed?",
        "Why’s this mess their mirror?",
        "How come they won’t leap?",
        "What if they burned it down?",
        "Who’s wild enough to win?",
        "Why’s this rut their road?",
        "What’s the truth they turn?",
        "How long till they bust out?",
        "Ever ask what’s the catch?",
        "What’s the doubt they drag?",
        "Why do they dodge this spark?",
        "How’s this snag still sharp?",
        "What if they flipped it fast?",
        "Who’s got the guts to grab?",
        "Why’s this fight their fate?",
        "What’s the block they bend?",
        "How come they can’t shift?",
        "Ever wonder what’s the fix?",
        "What’s the trap they trust?",
        "Why’s this grind still growling?",
        "How long till they break loose?",
        "What if they cut it clean?",
        "Who’s bold enough to bust?",
        "Why’s this mess their muse?",
        "What’s the lie they love?",
        "How do they skip this step?",
        "Ever think they’re too scared?",
        "What’s the rut they ride?",
        "Why’s this pain their pulse?",
        "How come they won’t wake?",
        "What if they owned the mess?",
        "Who’s got the spark to snap?",
        "Why’s this trap their truth?",
        "What’s the doubt they duck?",
        "How long till they flip it?",
        "Ever ask why they’re lost?"
    ],
    insight: [
        "Drop a truth that twists their view.",
        "Reveal a thread they’ve never pulled.",
        "Show a spark that shifts it all.",
        "Hand them a lens that lights up.",
        "Cut a gem that cuts through.",
        "Point to a flip they’ve flipped.",
        "Give a peek that’s pure gold.",
        "Tease a turn they’ve turned blind.",
        "Unveil a dot they didn’t dot.",
        "Serve a slice that slices deep.",
        "Drop a hint that hits hard.",
        "Reveal a crack they can’t unsee.",
        "Show a twist that’s too true.",
        "Hand them a spark that stings.",
        "Cut a truth that’s crystal sharp.",
        "Point to a shift that shocks.",
        "Give a gleam that glows raw.",
        "Tease a thread that threads it.",
        "Unveil a flip that flips them.",
        "Serve a gem that grips tight.",
        "Drop a peek that’s pure fire.",
        "Reveal a turn they’ve tuned out.",
        "Show a crack that cracks it.",
        "Hand them a lens that lands.",
        "Cut a hint that hooks deep.",
        "Point to a truth that bites.",
        "Give a twist that twists fate.",
        "Tease a spark that sparks up.",
        "Unveil a dot that dots it.",
        "Serve a slice that sings loud.",
        "Drop a shift that shifts fast.",
        "Reveal a gleam that gleams bright.",
        "Show a thread that threads through.",
        "Hand them a flip that flies.",
        "Cut a gem that gets them.",
        "Point to a turn that turns it.",
        "Give a crack that cracks open.",
        "Tease a truth that stuns them.",
        "Unveil a hint that hums raw.",
        "Serve a spark that snaps back.",
        "Drop a lens that lights it.",
        "Reveal a twist that twists free.",
        "Show a peek that peaks high.",
        "Hand them a shift that shifts now.",
        "Cut a thread that threads gold.",
        "Point to a flip that flips fast.",
        "Give a gem that glows hot.",
        "Tease a crack that cracks wide.",
        "Unveil a turn that turns heads.",
        "Serve a hint that hits home.",
        "Drop a truth that bites deep.",
        "Reveal a spark that sparks wild.",
        "Show a lens that lands hard.",
        "Hand them a twist that twists up.",
        "Cut a gleam that gleams sharp.",
        "Point to a thread that threads tight.",
        "Give a flip that flies free.",
        "Tease a gem that grips them.",
        "Unveil a peek that peaks out.",
        "Serve a shift that shifts gold.",
        "Drop a crack that cracks through.",
        "Reveal a hint that hums hot.",
        "Show a turn that turns sharp.",
        "Hand them a truth that stings fast.",
        "Cut a spark that snaps loud.",
        "Point to a lens that lights raw.",
        "Give a twist that twists gold.",
        "Tease a thread that threads it.",
        "Unveil a flip that flips free.",
        "Serve a gem that gets deep.",
        "Drop a peek that peaks wild.",
        "Reveal a shift that shifts them.",
        "Show a crack that cracks gold.",
        "Hand them a hint that hits sharp.",
        "Cut a truth that bites raw.",
        "Point to a turn that turns fast.",
        "Give a spark that sparks them.",
        "Tease a lens that lands hot.",
        "Unveil a twist that twists it.",
        "Serve a thread that threads free.",
        "Drop a flip that flies high.",
        "Reveal a gem that grips raw.",
        "Show a peek that peaks them.",
        "Hand them a crack that cracks it.",
        "Cut a shift that shifts sharp.",
        "Point to a hint that hums gold.",
        "Give a truth that stings them.",
        "Tease a spark that snaps free.",
        "Unveil a lens that lights up.",
        "Serve a twist that twists raw.",
        "Drop a thread that threads hot.",
        "Reveal a flip that flips them.",
        "Show a gem that gets wild.",
        "Hand them a turn that turns gold.",
        "Cut a peek that peaks sharp.",
        "Point to a crack that cracks free.",
        "Give a hint that hits them.",
        "Tease a shift that shifts it.",
        "Unveil a truth that bites gold.",
        "Serve a spark that snaps them."
    ],
    takeaway: [
        "Sum it up in a line that sticks.",
        "Leave them with a spark that burns.",
        "Drop a gem they’ll carry home.",
        "Hand them a truth that haunts.",
        "Cut a hook that hooks deep.",
        "Give a bite that bites back.",
        "Point to a win that wows them.",
        "Tease a twist that twists fate.",
        "Wrap it in a quip that quips.",
        "Serve a spark that sings loud.",
        "Sum it with a sting that stings.",
        "Leave a thread that threads it.",
        "Drop a truth that trips them.",
        "Hand them a gem that glows.",
        "Cut a line that lands hard.",
        "Give a hook that hooks tight.",
        "Point to a twist that turns it.",
        "Tease a bite that bites gold.",
        "Wrap it in a spark that snaps.",
        "Serve a win that winks back.",
        "Sum it with a quip that cuts.",
        "Leave a gem that grips them.",
        "Drop a thread that threads free.",
        "Hand them a truth that bites.",
        "Cut a spark that sings sharp.",
        "Give a line that lands gold.",
        "Point to a hook that hooks them.",
        "Tease a twist that twists free.",
        "Wrap it in a bite that burns.",
        "Serve a gem that glows hot.",
        "Sum it with a sting that snaps.",
        "Leave a win that wows fast.",
        "Drop a truth that trips gold.",
        "Hand them a spark that stings.",
        "Cut a quip that cuts deep.",
        "Give a thread that threads them.",
        "Point to a gem that grips raw.",
        "Tease a line that lands them.",
        "Wrap it in a hook that hooks.",
        "Serve a twist that turns gold.",
        "Sum it with a bite that bites.",
        "Leave a spark that sings free.",
        "Drop a gem that glows them.",
        "Hand them a truth that haunts.",
        "Cut a win that wows sharp.",
        "Give a quip that cuts them.",
        "Point to a thread that threads it.",
        "Tease a spark that snaps gold.",
        "Wrap it in a line that lands.",
        "Serve a hook that hooks raw.",
        "Sum it with a twist that turns.",
        "Leave a bite that bites them.",
        "Drop a truth that trips fast.",
        "Hand them a gem that grips it.",
        "Cut a spark that sings hot.",
        "Give a win that wows them.",
        "Point to a quip that cuts gold.",
        "Tease a thread that threads free.",
        "Wrap it in a gem that glows.",
        "Serve a line that lands sharp.",
        "Sum it with a hook that hooks.",
        "Leave a twist that turns them.",
        "Drop a bite that bites gold.",
        "Hand them a spark that snaps.",
        "Cut a truth that trips raw.",
        "Give a gem that grips them.",
        "Point to a win that wows it.",
        "Tease a quip that cuts free.",
        "Wrap it in a spark that sings.",
        "Serve a thread that threads gold.",
        "Sum it with a line that lands.",
        "Leave a hook that hooks them.",
        "Drop a twist that turns fast.",
        "Hand them a bite that bites.",
        "Cut a gem that glows sharp.",
        "Give a truth that haunts gold.",
        "Point to a spark that snaps it.",
        "Tease a win that wows them.",
        "Wrap it in a quip that cuts.",
        "Serve a line that lands them.",
        "Sum it with a thread that threads.",
        "Leave a gem that grips gold.",
        "Drop a spark that sings free.",
        "Hand them a twist that turns.",
        "Cut a bite that bites raw.",
        "Give a hook that hooks gold.",
        "Point to a truth that trips it.",
        "Tease a gem that glows them.",
        "Wrap it in a win that wows.",
        "Serve a quip that cuts sharp.",
        "Sum it with a spark that snaps.",
        "Leave a line that lands gold.",
        "Drop a thread that threads them.",
        "Hand them a bite that bites.",
        "Cut a twist that turns free.",
        "Give a gem that grips raw.",
        "Point to a hook that hooks it.",
        "Tease a truth that haunts them.",
        "Wrap it in a spark that sings.",
        "Serve a win that wows gold."
    ],
    listItem: [
        "Kick it off with a quick win.",
        "Throw in an unexpected hack.",
        "Add a twist they won’t see.",
        "Drop a tip that’s pure gold.",
        "Mix in a truth that stings.",
        "Lead with a move that shocks.",
        "Toss a gem they’ll grab fast.",
        "Sneak in a trick that flips.",
        "Pile on a tweak that works.",
        "Start with a bang they feel.",
        "Add a play that pays off.",
        "Drop a hack that hits hard.",
        "Mix in a step that shines.",
        "Lead with a truth that cuts.",
        "Toss a win they can taste.",
        "Sneak in a fix that sticks.",
        "Pile on a spark that burns.",
        "Start with a jolt they crave.",
        "Add a tip that turns heads.",
        "Drop a twist that wakes them.",
        "Mix in a play that bites.",
        "Lead with a hack that hums.",
        "Toss a gem that grips tight.",
        "Sneak in a move that lands.",
        "Pile on a trick that sings.",
        "Start with a win that pops.",
        "Add a tweak that’s too slick.",
        "Drop a step that’s pure fire.",
        "Mix in a truth that grips.",
        "Lead with a fix that flies.",
        "Toss a play that turns it.",
        "Sneak in a tip that stuns.",
        "Pile on a hack that heals.",
        "Start with a twist that hooks.",
        "Add a gem that glows bright.",
        "Drop a move that cuts deep.",
        "Mix in a win that wows.",
        "Lead with a spark that snaps.",
        "Toss a trick that takes off.",
        "Sneak in a step that sings.",
        "Pile on a fix that flies.",
        "Start with a hack that hits.",
        "Add a play that pops loud.",
        "Drop a tip that turns it.",
        "Mix in a twist that bites.",
        "Lead with a gem that grips.",
        "Toss a move that melts.",
        "Sneak in a tweak that works.",
        "Pile on a win that wows.",
        "Start with a truth that stings.",
        "Add a step that’s pure rush.",
        "Drop a hack that hooks tight.",
        "Mix in a spark that shines.",
        "Lead with a trick that flips.",
        "Toss a fix that lands hard.",
        "Sneak in a play that peaks.",
        "Pile on a tip that cuts.",
        "Start with a twist that turns.",
        "Add a gem that glows hot.",
        "Drop a move that bites fast.",
        "Mix in a win that sings.",
        "Lead with a hack that heals.",
        "Toss a step that’s too slick.",
        "Sneak in a truth that grips.",
        "Pile on a fix that flies.",
        "Start with a play that pops.",
        "Add a tweak that turns heads.",
        "Drop a tip that’s pure gold.",
        "Mix in a twist that wakes.",
        "Lead with a spark that snaps.",
        "Toss a gem that hits home.",
        "Sneak in a move that stuns.",
        "Pile on a hack that hums.",
        "Start with a win that bites.",
        "Add a step that cuts deep.",
        "Drop a trick that turns it.",
        "Mix in a fix that shines.",
        "Lead with a play that grips.",
        "Toss a twist that hooks.",
        "Sneak in a tip that flies.",
        "Pile on a gem that glows.",
        "Start with a hack that sings.",
        "Add a move that pops off.",
        "Drop a step that’s pure fire.",
        "Mix in a truth that bites.",
        "Lead with a tweak that works.",
        "Toss a win that turns heads.",
        "Sneak in a fix that stings.",
        "Pile on a spark that cuts.",
        "Start with a tip that hooks.",
        "Add a play that hits hard.",
        "Drop a gem that wakes them.",
        "Mix in a twist that grips.",
        "Lead with a step that flies.",
        "Toss a hack that turns it.",
        "Sneak in a move that shines.",
        "Pile on a trick that pops.",
        "Start with a win that glows."
    ],
    myth: [
        "Pick a belief everyone swears by.",
        "Target a cliché that’s overdue.",
        "Call out a tale they’ve bought.",
        "Smash a rule they cling to.",
        "Expose a lie they’ve lived.",
        "Bust a fad that’s faded.",
        "Rip into a habit they defend.",
        "Challenge a ‘truth’ they trust.",
        "Flip a story they’ve slept on.",
        "Shatter a myth that’s held them.",
        "Pick a trope that’s too tired.",
        "Target a line they lean on.",
        "Call out a scam they’ve swallowed.",
        "Smash a crutch they can’t drop.",
        "Expose a tale that’s too tall.",
        "Bust a belief that binds them.",
        "Rip into a fad they follow.",
        "Challenge a rule that rules them.",
        "Flip a lie they’ve loved.",
        "Shatter a cliché they chase.",
        "Pick a myth that’s pure fluff.",
        "Target a habit they hoard.",
        "Call out a ‘fact’ they fake.",
        "Smash a story that’s stale.",
        "Expose a line that’s lost it.",
        "Bust a trope they’re trapped.",
        "Rip into a belief they build.",
        "Challenge a fad that’s flat.",
        "Flip a rule they’ve run.",
        "Shatter a tale they tell.",
        "Pick a lie that’s loud now.",
        "Target a crutch they clutch.",
        "Call out a myth they mimic.",
        "Smash a habit that haunts.",
        "Expose a ‘truth’ they tout.",
        "Bust a cliché that’s crumbling.",
        "Rip into a story they spin.",
        "Challenge a belief that blinds.",
        "Flip a fad they’re fond.",
        "Shatter a line they live.",
        "Pick a rule that’s ridiculous.",
        "Target a tale that’s tired.",
        "Call out a lie they lap.",
        "Smash a trope that’s trash.",
        "Expose a myth that’s mush.",
        "Bust a habit they hide.",
        "Rip into a ‘fact’ they flaunt.",
        "Challenge a story that’s stuck.",
        "Flip a crutch they crave.",
        "Shatter a belief they bank.",
        "Pick a fad that’s fizzled.",
        "Target a ‘truth’ they trust.",
        "Call out a rule they ride.",
        "Smash a lie that lingers.",
        "Expose a cliché they chase.",
        "Bust a tale that’s tame.",
        "Rip into a myth they make.",
        "Challenge a habit that holds.",
        "Flip a line that’s lame.",
        "Shatter a story they sell.",
        "Pick a trope that’s too much.",
        "Target a belief they bend.",
        "Call out a fad they feed.",
        "Smash a ‘fact’ they fight.",
        "Expose a rule that’s rotten.",
        "Bust a crutch they carry.",
        "Rip into a tale they tout.",
        "Challenge a lie that lasts.",
        "Flip a myth that’s mild.",
        "Shatter a habit they hug.",
        "Pick a ‘truth’ that’s thin.",
        "Target a story they stand.",
        "Call out a cliché they claim.",
        "Smash a belief that breaks.",
        "Expose a fad that’s fake.",
        "Bust a line they love.",
        "Rip into a rule they run.",
        "Challenge a trope that’s toast.",
        "Flip a tale that’s tepid.",
        "Shatter a ‘fact’ they flaunt.",
        "Pick a lie that’s loose.",
        "Target a myth they mold.",
        "Call out a habit they hold.",
        "Smash a crutch that’s cracked.",
        "Expose a story that’s soft.",
        "Bust a ‘truth’ they build.",
        "Rip into a fad that flops.",
        "Challenge a belief they bet.",
        "Flip a rule that’s rigid.",
        "Shatter a tale they trust.",
        "Pick a cliché that’s cheap.",
        "Target a lie they lift.",
        "Call out a trope they take.",
        "Smash a myth that’s moot.",
        "Expose a habit that hurts.",
        "Bust a line that’s limp.",
        "Rip into a ‘fact’ they fake.",
        "Challenge a story that sinks."
    ],
    fact: [
        "Hit them with a truth that’s fresh.",
        "Back it up with a quick hit.",
        "Drop a stat that slaps hard.",
        "Reveal a find they can’t deny.",
        "Show a proof that pops off.",
        "Point to a fact that bites.",
        "Give a nugget that’s pure gold.",
        "Lay out a truth that lands.",
        "Cut a data point that cuts.",
        "Serve a real that’s raw as hell.",
        "Hit them with a number that stings.",
        "Back it with a source they trust.",
        "Drop a truth that turns heads.",
        "Reveal a stat that shocks them.",
        "Show a find that flips it.",
        "Point to a proof that grips.",
        "Give a fact that’s fierce fun.",
        "Lay out a real that sticks.",
        "Cut a nugget that’s too true.",
        "Serve a data that drives home.",
        "Hit them with a truth that burns.",
        "Back it up with a hard hit.",
        "Drop a stat that stops them.",
        "Reveal a find that wakes them.",
        "Show a proof that punches.",
        "Point to a fact that flips fast.",
        "Give a real that’s razor sharp.",
        "Lay out a truth that bites deep.",
        "Cut a data that digs in.",
        "Serve a nugget that nails it.",
        "Hit them with a number that shocks.",
        "Back it with a truth they feel.",
        "Drop a find that flips their day.",
        "Reveal a stat that stuns them.",
        "Show a proof that’s pure fire.",
        "Point to a real that resonates.",
        "Give a fact that’s fast gold.",
        "Lay out a data that lands hard.",
        "Cut a truth that turns it.",
        "Serve a stat that sings loud.",
        "Hit them with a find that hooks.",
        "Back it up with a raw edge.",
        "Drop a proof that pops off.",
        "Reveal a number that bites back.",
        "Show a fact that flips fate.",
        "Point to a truth that twists.",
        "Give a real that’s right now.",
        "Lay out a stat that stings sharp.",
        "Cut a nugget that cuts through.",
        "Serve a data that drives it.",
        "Hit them with a truth that grips.",
        "Back it with a find that fits.",
        "Drop a stat that slaps them.",
        "Reveal a proof that peaks high.",
        "Show a real that rocks them.",
        "Point to a fact that fires up.",
        "Give a number that’s no joke.",
        "Lay out a truth that turns gold.",
        "Cut a data that digs deep.",
        "Serve a find that flies free.",
        "Hit them with a stat that sticks.",
        "Back it up with a hard truth.",
        "Drop a real that rips through.",
        "Reveal a proof that pulls them.",
        "Show a fact that flips quick.",
        "Point to a nugget that nails.",
        "Give a truth that’s too tight.",
        "Lay out a stat that shocks fast.",
        "Cut a find that cuts clean.",
        "Serve a data that drives hard.",
        "Hit them with a real that bites.",
        "Back it with a number that lands.",
        "Drop a proof that pops them.",
        "Reveal a stat that stuns quick.",
        "Show a truth that turns sharp.",
        "Point to a fact that grips raw.",
        "Give a find that flies high.",
        "Lay out a real that resonates.",
        "Cut a nugget that’s pure rush.",
        "Serve a stat that sings gold.",
        "Hit them with a data that hooks.",
        "Back it up with a truth that cuts.",
        "Drop a proof that peaks them.",
        "Reveal a number that bites gold.",
        "Show a fact that flips them.",
        "Point to a real that fires off.",
        "Give a stat that’s stone solid.",
        "Lay out a find that lands gold.",
        "Cut a truth that twists fate.",
        "Serve a data that drives free.",
        "Hit them with a proof that grips.",
        "Back it with a stat that stings.",
        "Drop a real that rips fast.",
        "Reveal a fact that turns it.",
        "Show a nugget that nails them.",
        "Point to a truth that pops off.",
        "Give a find that flies sharp.",
        "Lay out a stat that shocks them.",
        "Cut a proof that cuts gold."
    ]
};
const recentPrompts = {
    hook: [],
    story: [],
    lesson: [],
    action: [],
    problem: [],
    agitation: [],
    solution: [],
    question: [],
    insight: [],
    takeaway: [],
    listItem: [],
    myth: [],
    fact: [],
    you: []
};

function getRandomPrompt(type) {
    const prompts = creativePrompts[type] || [];
    if (prompts.length === 0) return "Get creative here!";

    const maxAttempts = 10;
    let attempt = 0;
    let selectedPrompt;

    do {
        selectedPrompt = prompts[Math.floor(Math.random() * prompts.length)];
        attempt++;
        if (attempt >= maxAttempts || !recentPrompts[type].includes(selectedPrompt)) {
            break;
        }
    } while (true);

    if (recentPrompts[type].length >= 10) {
        recentPrompts[type].shift();
    }
    recentPrompts[type].push(selectedPrompt);

    return selectedPrompt;
}

function generateStructure() {
    const description = document.getElementById('description').value.trim();
    const format = document.getElementById('format').value;
    let output = '';

    if (!description) {
        output = 'Please enter a description!';
    } else {
        switch (format) {
            case 'hook-story-lesson-action':
                output = `- Hook: Grab them with a bold opener\n  *${getRandomPrompt('hook')}*\n` +
                         `- Story: Share your journey\n  *${getRandomPrompt('story')}*\n` +
                         `- Lesson: Reveal the core truth\n  *${getRandomPrompt('lesson')}*\n` +
                         `- Actionable You: Give one clear step\n  *${getRandomPrompt('action')}*`;
                break;
            case 'problem-agitation-solution':
                output = `- Problem: Name the struggle\n  *${getRandomPrompt('problem')}*\n` +
                         `- Agitation: Turn up the heat\n  *${getRandomPrompt('agitation')}*\n` +
                         `- Solution: Deliver the fix\n  *${getRandomPrompt('solution')}*`;
                break;
            case 'question-insight-takeaway':
                output = `- Question: Spark their curiosity\n  *${getRandomPrompt('question')}*\n` +
                         `- Insight: Offer a fresh angle\n  *${getRandomPrompt('insight')}*\n` +
                         `- Takeaway: Leave them with a gem\n  *${getRandomPrompt('takeaway')}*`;
                break;
            case 'listicle':
                output = `- Title: Craft a catchy list headline\n  *${getRandomPrompt('listItem')}*\n` +
                         `- Item 1: Lead with a strong tip\n  *${getRandomPrompt('listItem')}*\n` +
                         `- Item 2: Add a practical idea\n  *${getRandomPrompt('listItem')}*\n` +
                         `- Item 3: Mix in a bold move\n  *${getRandomPrompt('listItem')}*\n` +
                         `- Item 4: Share a hidden gem\n  *${getRandomPrompt('listItem')}*\n` +
                         `- Item 5: End with a bang\n  *${getRandomPrompt('listItem')}*`;
                break;
            case 'myth-fact':
                output = `- Myth: Bust a common lie\n  *${getRandomPrompt('myth')}*\n` +
                         `- Fact: Drop the real deal\n  *${getRandomPrompt('fact')}*`;
                break;
            default:
                output = 'Select a valid format!';
        }
    }

    document.getElementById('output').textContent = output;
}
