const creativePrompts = {
    hook: [
        "Smack them with a wild ‘what if’ they can’t shake!",
        "Tease a secret they’ll beg to know.",
        "Start with a line that feels like a slap.",
        "Drop a stat that makes them gasp.",
        "Ask a question that stings a little.",
        "Flash a scene they’ve lived a hundred times.",
        "Lead with a promise too good to skip.",
        "Throw out a dare they can’t resist.",
        "Hint at a twist they won’t see coming.",
        "Open with a soundbite that sticks.",
        "Bait them with a juicy ‘you’ll never guess.’",
        "Shock them with a truth they’ve dodged.",
        "Paint a ‘holy crap’ moment in one line.",
        "Toss in a riddle they’ll itch to solve.",
        "Kick off with a shout they can’t ignore.",
        "Whisper something they’ll lean in for.",
        "Hit them with a ‘wait, what?’ hook.",
        "Frame it like a cliffhanger.",
        "Start with a brag that’s half-true.",
        "Ask what they’d kill to know.",
        "Drop a line that’s pure chaos.",
        "Lead with a glitch in their reality.",
        "Tease a fix they didn’t know they needed.",
        "Open with a punch they’ll feel.",
        "Spark a ‘no way’ reaction fast.",
        "Throw down a gauntlet they’ll grab.",
        "Start with a lie they’ve bought.",
        "Hook them with a ‘picture this.’",
        "Ask a question they’ve never dared.",
        "Blow their mind in ten words.",
        "Lead with a trap they’ll fall into.",
        "Drop a bomb they can’t unhear.",
        "Start with a confession that hooks.",
        "Tease a reveal that’s worth the wait.",
        "Ask what keeps them up at night.",
        "Open with a stat that flips the script.",
        "Hit them with a ‘you’re doing it wrong.’",
        "Spark a fight they’ll want to join.",
        "Lead with a whisper that screams.",
        "Throw in a ‘bet you didn’t know.’",
        "Start with a scene that’s too real.",
        "Ask a question that breaks the ice.",
        "Drop a truth they’ll hate to love.",
        "Tease a hack they’ll steal instantly.",
        "Open with a jab at the norm.",
        "Hit them with a ‘this changes everything.’",
        "Lead with a dare that bites.",
        "Spark a ‘wait, really?’ moment.",
        "Ask what they’d trade their soul for.",
        "Throw out a line that haunts.",
        "Start with a stat that’s pure fire.",
        "Tease a story they’ll chase.",
        "Drop a question that hooks deep.",
        "Open with a twist they’ll replay.",
        "Hit them with a ‘you’re not alone.’",
        "Lead with a secret they’ll crave.",
        "Ask a ‘what if’ that lingers.",
        "Throw in a hook that’s pure gold.",
        "Start with a line they’ll quote.",
        "Drop a hint that’s a game-changer.",
        "Tease a truth they’ve missed.",
        "Open with a bang they’ll feel.",
        "Ask something that flips their world.",
        "Hit them with a ‘trust me’ vibe.",
        "Lead with a stat that shocks.",
        "Throw out a dare that sticks.",
        "Start with a scene they’ll see.",
        "Drop a line that’s raw and real.",
        "Tease a fix that’s too easy.",
        "Ask a question that’s a hook itself.",
        "Open with a ‘you’ve been lied to.’",
        "Hit them with a truth that burns.",
        "Lead with a whisper that roars.",
        "Throw in a stat they’ll double-check.",
        "Start with a dare they’ll take.",
        "Drop a hook that’s pure bait.",
        "Tease a twist that’s sneaky.",
        "Ask what they’d kill to fix.",
        "Open with a line that bites.",
        "Hit them with a ‘this is it’ moment.",
        "Lead with a question that haunts.",
        "Throw out a stat that flips.",
        "Start with a scene that grabs.",
        "Drop a truth they’ll wrestle with.",
        "Tease a hack that’s pure magic.",
        "Ask a ‘why not’ that stings.",
        "Open with a bang that echoes.",
        "Hit them with a line that lands.",
        "Lead with a secret that pulls.",
        "Throw in a dare that sparks.",
        "Start with a stat that’s wild.",
        "Drop a question that hooks deep.",
        "Tease a fix they’ll jump at.",
        "Ask something that’s pure fire.",
        "Open with a twist that shocks.",
        "Hit them with a truth they need.",
        "Lead with a line that’s bold.",
        "Throw out a hook that sings.",
        "Start with a scene that’s alive.",
        "Drop a dare they’ll run with."
    ],
    story: [
        "Tell the day you crashed and burned.",
        "Spill a moment you’d rather forget.",
        "Paint the time you laughed at failure.",
        "Share the fight that almost broke you.",
        "Zoom in on the second you woke up.",
        "Relive a win that felt impossible.",
        "Describe the mess that taught you most.",
        "Walk them through your dumbest mistake.",
        "Show the scar that shaped you.",
        "Tell a tale that’s still unfolding.",
        "Reveal the night you hit rock bottom.",
        "Sketch the moment you found gold.",
        "Share the stumble that saved you.",
        "Tell the time you ignored the signs.",
        "Paint a day that flipped your life.",
        "Relive the chaos you barely survived.",
        "Describe the win you didn’t expect.",
        "Spill the story that haunts you still.",
        "Show the fall that built you back.",
        "Tell a truth you learned the hard way.",
        "Reveal the day you broke the rules.",
        "Sketch a scene that’s pure grit.",
        "Share the moment you saw the light.",
        "Tell the fight you didn’t win.",
        "Paint the time you bet it all.",
        "Relive a loss that turned to gain.",
        "Describe the spark that changed you.",
        "Spill a tale of epic dumb luck.",
        "Show the step that started it all.",
        "Tell the day you said ‘screw it.’",
        "Reveal the mess you laughed through.",
        "Sketch the time you outran fate.",
        "Share the stumble that stuck.",
        "Tell a story that’s half a lie.",
        "Paint the moment you got hooked.",
        "Relive the day you threw it out.",
        "Describe the crash that woke you.",
        "Spill the fight you didn’t choose.",
        "Show the win that felt like theft.",
        "Tell a tale of pure defiance.",
        "Reveal the time you faked it.",
        "Sketch a day that’s all blur.",
        "Share the loss you still feel.",
        "Tell the moment you turned it.",
        "Paint the scene that broke you open.",
        "Relive the choice you can’t take back.",
        "Describe the luck that wasn’t luck.",
        "Spill a story that’s too weird.",
        "Show the fall you didn’t catch.",
        "Tell the day you found your edge.",
        "Reveal the time you ran blind.",
        "Sketch the fight that defined you.",
        "Share the win you didn’t earn.",
        "Tell a tale that’s pure guts.",
        "Paint the moment you snapped.",
        "Relive the day you said yes.",
        "Describe the mess you owned.",
        "Spill the stumble that soared.",
        "Show the truth you hid from.",
        "Tell the time you burned it down.",
        "Reveal the spark you stole.",
        "Sketch a scene that’s raw.",
        "Share the day you broke free.",
        "Tell the fight you lost big.",
        "Paint the win that wasn’t planned.",
        "Relive the moment you flipped.",
        "Describe the fall that fueled you.",
        "Spill a tale that’s all heart.",
        "Show the step you tripped on.",
        "Tell the day you saw it clear.",
        "Reveal the time you went rogue.",
        "Sketch the loss that lingered.",
        "Share the moment you grabbed it.",
        "Tell a story that’s half mad.",
        "Paint the scene you survived.",
        "Relive the choice that stuck.",
        "Describe the win you clawed for.",
        "Spill the day you laughed last.",
        "Show the fall that lifted you.",
        "Tell the time you said no.",
        "Reveal the mess you mastered.",
        "Sketch a tale of pure chance.",
        "Share the fight you started.",
        "Tell the moment you cracked.",
        "Paint the day you rebuilt.",
        "Relive the stumble you owned.",
        "Describe the truth you dodged.",
        "Spill a story that’s still hot.",
        "Show the win you snatched.",
        "Tell the time you went all in.",
        "Reveal the day you woke late.",
        "Sketch the scene that scarred.",
        "Share the loss you turned.",
        "Tell a tale that’s pure fire.",
        "Paint the moment you leapt.",
        "Relive the fight you won ugly.",
        "Describe the spark you chased.",
        "Spill the day you broke it.",
        "Show the step that shifted.",
        "Tell the time you ran wild."
    ],
    lesson: [
        "Strip it to a truth they can’t dodge.",
        "Turn their ‘duh’ into a ‘whoa.’",
        "Hand them a lens they didn’t have.",
        "Prove the obvious is a lie.",
        "Tie it to a fight they’re in.",
        "Make the complex stupidly simple.",
        "Flip the script they’ve memorized.",
        "Drop a line they’ll quote later.",
        "Show the thread that ties it all.",
        "Leave them nodding, then stunned.",
        "Reveal the catch they missed.",
        "Boil it down to raw bones.",
        "Smash a belief they cling to.",
        "Give them a truth that bites.",
        "Link it to their daily grind.",
        "Cut the fluff to one sharp point.",
        "Twist a cliché into gold.",
        "Drop a bomb that sticks around.",
        "Show the dot they didn’t connect.",
        "Hit them with a ‘now I get it.’",
        "Prove the hard way wins.",
        "Shrink it to a single spark.",
        "Break the rule they swear by.",
        "Hand them a truth that stings.",
        "Tie it to a fear they hide.",
        "Make it clear as a slap.",
        "Flip their ‘yes’ to ‘hell no.’",
        "Drop a takeaway that haunts.",
        "Show the piece they overlooked.",
        "Leave them with a shifted view.",
        "Reveal the lie they live.",
        "Cut it to a gut punch.",
        "Smash the myth they love.",
        "Give a lesson that burns.",
        "Link it to their next step.",
        "Strip it bare and bold.",
        "Twist the norm they trust.",
        "Drop a truth they’ll steal.",
        "Show the gap they didn’t see.",
        "Hit them with a clear ‘aha.’",
        "Prove the small stuff rules.",
        "Boil it to a hot take.",
        "Break the chain they’re stuck in.",
        "Hand them a spark that lasts.",
        "Tie it to a win they want.",
        "Make it simple but deep.",
        "Flip the game they play.",
        "Drop a line that echoes.",
        "Show the truth they ran from.",
        "Leave them with a new lens.",
        "Reveal the trick they missed.",
        "Cut it to a raw truth.",
        "Smash the crutch they lean on.",
        "Give a lesson they’ll feel.",
        "Link it to their chaos.",
        "Strip it to a single beat.",
        "Twist the tale they tell.",
        "Drop a gem that sticks.",
        "Show the flaw they ignored.",
        "Hit them with a ‘damn, really?’",
        "Prove the hustle pays off.",
        "Shrink it to a bold claim.",
        "Break the mold they fit.",
        "Hand them a truth that shifts.",
        "Tie it to their breaking point.",
        "Make it sharp as a knife.",
        "Flip the lie they bought.",
        "Drop a takeaway that sings.",
        "Show the step they skipped.",
        "Leave them with a hard yes.",
        "Reveal the edge they need.",
        "Cut it to a fierce point.",
        "Smash the trap they’re in.",
        "Give a lesson that lands.",
        "Link it to their fire.",
        "Strip it to a loud truth.",
        "Twist the path they know.",
        "Drop a line that cuts.",
        "Show the miss they made.",
        "Hit them with a ‘got it.’",
        "Prove the grit beats luck.",
        "Boil it to a tight hook.",
        "Break the wall they built.",
        "Hand them a spark that grows.",
        "Tie it to their doubt.",
        "Make it clear and wild.",
        "Flip the rule they follow.",
        "Drop a truth that roars.",
        "Show the turn they need.",
        "Leave them with a bold shift.",
        "Reveal the play they lost.",
        "Cut it to a hot spark.",
        "Smash the line they drew.",
        "Give a lesson that sticks.",
        "Link it to their edge.",
        "Strip it to a fierce beat.",
        "Twist the truth they hold.",
        "Drop a gem that bites.",
        "Show the gap they crossed.",
        "Hit them with a ‘yes, now.’"
    ],
    action: [
        "Give them a 5-minute win they can try.",
        "Make it so simple they can’t say no.",
        "Add a quirky twist to keep it fun.",
        "Tell them to ditch one thing today.",
        "Point to a tool they already own.",
        "Set a timer and watch them go.",
        "Break it into a bite they’ll chew.",
        "Sneak in a hack they’ll brag about.",
        "Push them to flip one switch now.",
        "Hand them a step that’s pure gold.",
        "Make it a dare they’ll jump at.",
        "Cut one habit they won’t miss.",
        "Give a trick that’s stupid easy.",
        "Tell them to start with a scribble.",
        "Point to a win they can grab.",
        "Set a goal that’s laughably small.",
        "Break it to a move they’ll make.",
        "Sneak in a fix that sparks joy.",
        "Push them to try it tonight.",
        "Hand them a play that pays off.",
        "Make it a game they’ll play.",
        "Cut the crap they overthink.",
        "Give a step that’s raw and real.",
        "Tell them to steal one idea.",
        "Point to a shift they’ll feel.",
        "Set a task that’s pure fire.",
        "Break it to a snap decision.",
        "Sneak in a tweak they’ll love.",
        "Push them to test it once.",
        "Hand them a win they’ll chase.",
        "Make it a move they can’t skip.",
        "Cut a lie they’ve lived.",
        "Give a hack that’s pure grit.",
        "Tell them to jump in blind.",
        "Point to a fix that sticks.",
        "Set a play that’s bold as hell.",
        "Break it to a quick hit.",
        "Sneak in a spark that sings.",
        "Push them to ditch the fluff.",
        "Hand them a step that bites.",
        "Make it a dare that lands.",
        "Cut one doubt they drag.",
        "Give a trick that’s too good.",
        "Tell them to flip it fast.",
        "Point to a win they’ll snag.",
        "Set a goal that’s dirt cheap.",
        "Break it to a hot move.",
        "Sneak in a fix that’s wild.",
        "Push them to try it raw.",
        "Hand them a play that hooks.",
        "Make it a step they’ll run.",
        "Cut a trap they’re stuck in.",
        "Give a hack that’s pure heat.",
        "Tell them to start with nada.",
        "Point to a shift that shocks.",
        "Set a task that’s all guts.",
        "Break it to a fast win.",
        "Sneak in a tweak that roars.",
        "Push them to leap today.",
        "Hand them a move that cuts.",
        "Make it a dare that sticks.",
        "Cut one fear they feed.",
        "Give a trick that’s pure rush.",
        "Tell them to grab it now.",
        "Point to a fix that’s tight.",
        "Set a play that’s all in.",
        "Break it to a sharp hit.",
        "Sneak in a spark that flies.",
        "Push them to ditch one lie.",
        "Hand them a win that sings.",
        "Make it a step that bites.",
        "Cut a doubt they haul.",
        "Give a hack that’s pure edge.",
        "Tell them to flip it loose.",
        "Point to a shift that burns.",
        "Set a goal that’s bare bones.",
        "Break it to a hot snap.",
        "Sneak in a fix that pops.",
        "Push them to try it loud.",
        "Hand them a play that grips.",
        "Make it a move that stings.",
        "Cut one block they trip on.",
        "Give a trick that’s all fire.",
        "Tell them to start with zip.",
        "Point to a win that’s close.",
        "Set a task that’s pure spark.",
        "Break it to a quick jab.",
        "Sneak in a tweak that hums.",
        "Push them to jump right in.",
        "Hand them a step that roars.",
        "Make it a dare that pulls.",
        "Cut a lie they lean on.",
        "Give a hack that’s pure rush.",
        "Tell them to grab it raw.",
        "Point to a fix that flies.",
        "Set a play that’s all heat.",
        "Break it to a fast spark.",
        "Sneak in a move that bites.",
        "Push them to ditch the noise.",
        "Hand them a win that lands."
    ],
    listItem: [
        "Kick it off with a quick win.",
        "Throw in an unexpected hack.",
        "End with a bold, game-changing move.",
        "Drop a tip they’ll use today.",
        "Sneak in a gem they’ll steal.",
        "Lead with a fix that’s pure gold.",
        "Add a twist they won’t see.",
        "Close with a bang they’ll feel.",
        "Give a trick that’s stupid simple.",
        "Toss in a play that sticks.",
        "Start with a spark that hooks.",
        "Slip in a hack that bites.",
        "Finish with a truth that lands.",
        "Drop a move they’ll try fast.",
        "Sneak in a tip that sings.",
        "Lead with a win they crave.",
        "Add a tweak that’s pure fire.",
        "End with a step that shifts.",
        "Give a hack that’s all guts.",
        "Toss in a gem that roars.",
        "Start with a fix that stings.",
        "Slip in a play that burns.",
        "Close with a move that cuts.",
        "Drop a tip that’s raw and real.",
        "Sneak in a trick that flies.",
        "Lead with a spark that pulls.",
        "Add a twist that shocks.",
        "Finish with a win that bites.",
        "Give a move that’s pure heat.",
        "Toss in a hack that grips.",
        "Start with a tip that lands.",
        "Slip in a gem that hums.",
        "End with a play that sticks.",
        "Drop a fix that’s too easy.",
        "Sneak in a step that pops.",
        "Lead with a trick that hooks.",
        "Add a tweak that’s all rush.",
        "Close with a tip that sings.",
        "Give a hack that’s bare bones.",
        "Toss in a move that roars.",
        "Start with a win that flies.",
        "Slip in a play that bites.",
        "Finish with a fix that burns.",
        "Drop a tip that’s pure spark.",
        "Sneak in a gem that shifts.",
        "Lead with a step that cuts.",
        "Add a twist that’s pure grit.",
        "End with a hack that lands.",
        "Give a move that’s all fire.",
        "Toss in a trick that pulls.",
        "Start with a fix that stings.",
        "Slip in a tip that shocks.",
        "Close with a win that grips.",
        "Drop a hack that’s raw heat.",
        "Sneak in a play that sings.",
        "Lead with a gem that bites.",
        "Add a tweak that flies.",
        "Finish with a step that roars.",
        "Give a tip that’s pure rush.",
        "Toss in a move that hooks.",
        "Start with a trick that burns.",
        "Slip in a fix that lands.",
        "End with a play that shifts.",
        "Drop a win that’s too good.",
        "Sneak in a hack that cuts.",
        "Lead with a tip that pulls.",
        "Add a twist that’s all guts.",
        "Close with a gem that sticks.",
        "Give a step that’s pure spark.",
        "Toss in a play that bites.",
        "Start with a fix that roars.",
        "Slip in a move that sings.",
        "Finish with a trick that flies.",
        "Drop a tip that’s bare heat.",
        "Sneak in a win that shocks.",
        "Lead with a hack that grips.",
        "Add a tweak that lands.",
        "End with a step that burns.",
        "Give a gem that’s all fire.",
        "Toss in a fix that pulls.",
        "Start with a play that cuts.",
        "Slip in a tip that roars.",
        "Close with a move that sings.",
        "Drop a trick that’s pure rush.",
        "Sneak in a step that bites.",
        "Lead with a win that flies.",
        "Add a hack that shifts.",
        "Finish with a gem that hooks.",
        "Give a tip that’s raw grit.",
        "Toss in a play that lands.",
        "Start with a fix that burns.",
        "Slip in a move that sticks.",
        "End with a trick that pulls.",
        "Drop a win that’s all heat.",
        "Sneak in a hack that sings.",
        "Lead with a step that roars.",
        "Add a tweak that bites.",
        "Close with a tip that flies.",
        "Give a gem that’s pure spark.",
        "Toss in a fix that grips."
    ],
    myth: [
        "Pick a belief everyone swears by.",
        "Target a cliché that’s overdue.",
        "Start with ‘They say…’ and debunk.",
        "Call out a lie they’ve all bought.",
        "Smash a myth that’s pure fluff.",
        "Reveal the tale they repeat blind.",
        "Bust a rule they cling to.",
        "Expose a fad that’s all noise.",
        "Flip a ‘truth’ they’ve swallowed.",
        "Drop a myth that’s past due.",
        "Hit a belief that Chimere hype.",
        "Target a line they’ve memorized.",
        "Start with a sham they trust.",
        "Call out a trick they’ve fallen for.",
        "Smash a tale that’s too old.",
        "Reveal a lie they live by.",
        "Bust a claim that’s all air.",
        "Expose a rule that’s broke.",
        "Flip a myth that’s stuck hard.",
        "Drop a belief they won’t ditch.",
        "Hit a cliché that’s pure dust.",
        "Target a ‘fact’ they lean on.",
        "Start with a yarn they spin.",
        "Call out a trap they’re in.",
        "Smash a line that’s pure bunk.",
        "Reveal a myth that’s too loud.",
        "Bust a tale that’s all smoke.",
        "Expose a lie they’ve loved.",
        "Flip a rule that’s gone soft.",
        "Drop a sham that’s still hot.",
        "Hit a belief that’s pure mess.",
        "Target a myth they won’t quit.",
        "Start with a ‘truth’ they eat.",
        "Call out a fad that’s dead.",
        "Smash a claim that’s too weak.",
        "Reveal a line they’ve bought.",
        "Bust a myth that’s pure flash.",
        "Expose a tale that’s all spin.",
        "Flip a lie they’ve held.",
        "Drop a rule that’s pure rot.",
        "Hit a cliché that’s burned out.",
        "Target a belief they can’t shake.",
        "Start with a sham they swear.",
        "Call out a myth that’s stale.",
        "Smash a ‘fact’ that’s pure gas.",
        "Reveal a trap they’ve missed.",
        "Bust a line that’s too thin.",
        "Expose a rule that’s all hype.",
        "Flip a tale that’s worn out.",
        "Drop a lie they’ve clung to.",
        "Hit a myth that’s pure noise.",
        "Target a claim they repeat.",
        "Start with a fad they follow.",
        "Call out a belief that’s flat.",
        "Smash a sham that’s too big.",
        "Reveal a ‘truth’ they trust.",
        "Bust a myth that’s all fluff.",
        "Expose a line that’s gone cold.",
        "Flip a rule that’s pure junk.",
        "Drop a tale that’s too much.",
        "Hit a lie that’s still alive.",
        "Target a myth they’ve built.",
        "Start with a trap they love.",
        "Call out a fad that’s fake.",
        "Smash a belief that’s soft.",
        "Reveal a claim that’s thin.",
        "Bust a ‘fact’ that’s pure air.",
        "Expose a sham that’s loud.",
        "Flip a myth that’s old news.",
        "Drop a line they won’t drop.",
        "Hit a rule that’s pure dust.",
        "Target a tale they tell.",
        "Start with a lie they hold.",
        "Call out a myth that’s weak.",
        "Smash a fad that’s done.",
        "Reveal a belief that’s off.",
        "Bust a trap that’s tight.",
        "Expose a ‘truth’ that’s bent.",
        "Flip a claim that’s stale.",
        "Drop a sham that’s cooked.",
        "Hit a myth that’s pure spin.",
        "Target a rule they ride.",
        "Start with a tale that’s bunk.",
        "Call out a lie that’s hot.",
        "Smash a belief that’s loose.",
        "Reveal a fad that’s cold.",
        "Bust a line that’s pure hype.",
        "Expose a myth that’s flat.",
        "Flip a ‘fact’ that’s gone.",
        "Drop a trap they’ve set.",
        "Hit a sham that’s pure noise.",
        "Target a claim they’ve kept.",
        "Start with a myth they eat.",
        "Call out a rule that’s dead.",
        "Smash a tale that’s soft.",
        "Reveal a lie that’s loud.",
        "Bust a fad that’s thin.",
        "Expose a belief that’s weak.",
        "Flip a sham that’s old.",
        "Drop a ‘truth’ that’s toast."
    ],
    fact: [
        "Hit them with a truth that’s fresh.",
        "Back it up with a quick hit.",
        "Make it counterintuitive and crisp.",
        "Drop a stat that’s pure heat.",
        "Reveal a find they can’t deny.",
        "Give a fact that flips the game.",
        "Show a truth that’s raw and real.",
        "Prove it with a tight example.",
        "Cut it to a bold, hard truth.",
        "Hand them a gem that sticks.",
        "Hit with a line that’s pure fire.",
        "Back it with a stat they’ll check.",
        "Make it a twist they’ll feel.",
        "Drop a truth that’s all guts.",
        "Reveal a fact that bites.",
        "Give a find that’s too sharp.",
        "Show a stat that shocks them.",
        "Prove it with a real snap.",
        "Cut it to a truth that lands.",
        "Hand them a fact that sings.",
        "Hit with a gem that burns.",
        "Back it up with a hot take.",
        "Make it a truth that stings.",
        "Drop a stat that’s pure spark.",
        "Reveal a find that roars.",
        "Give a fact that’s all edge.",
        "Show a twist that’s too good.",
        "Prove it with a fast jab.",
        "Cut it to a line that hooks.",
        "Hand them a truth that flies.",
        "Hit with a stat that pulls.",
        "Back it with a raw hit.",
        "Make it a find that cuts.",
        "Drop a fact that’s pure rush.",
        "Reveal a gem that grips.",
        "Give a truth that’s bare heat.",
        "Show a stat that shifts.",
        "Prove it with a tight spark.",
        "Cut it to a fact that bites.",
        "Hand them a line that sticks.",
        "Hit with a find that roars.",
        "Back it up with a bold snap.",
        "Make it a truth that flies.",
        "Drop a stat that’s all fire.",
        "Reveal a fact that lands.",
        "Give a gem that’s pure grit.",
        "Show a twist that burns.",
        "Prove it with a quick truth.",
        "Cut it to a stat that sings.",
        "Hand them a find that shocks.",
        "Hit with a truth that grips.",
        "Back it with a real stat.",
        "Make it a fact that pulls.",
        "Drop a line that’s pure heat.",
        "Reveal a gem that bites.",
        "Give a stat that’s too raw.",
        "Show a truth that sticks.",
        "Prove it with a fast hit.",
        "Cut it to a find that roars.",
        "Hand them a fact that shifts.",
        "Hit with a stat that sings.",
        "Back it up with a tight jab.",
        "Make it a truth that burns.",
        "Drop a gem that’s all spark.",
        "Reveal a find that flies.",
        "Give a fact that’s pure rush.",
        "Show a stat that grips.",
        "Prove it with a bold truth.",
        "Cut it to a line that lands.",
        "Hand them a truth that cuts.",
        "Hit with a gem that pulls.",
        "Back it with a raw snap.",
        "Make it a fact that bites.",
        "Drop a stat that’s pure grit.",
        "Reveal a find that sticks.",
        "Give a truth that’s too hot.",
        "Show a twist that shifts.",
        "Prove it with a quick spark.",
        "Cut it to a stat that flies.",
        "Hand them a fact that roars.",
        "Hit with a line that burns.",
        "Back it up with a real hit.",
        "Make it a gem that sings.",
        "Drop a truth that’s all fire.",
        "Reveal a stat that lands.",
        "Give a find that’s pure edge.",
        "Show a fact that pulls.",
        "Prove it with a tight snap.",
        "Cut it to a truth that grips.",
        "Hand them a stat that bites.",
        "Hit with a gem that flies.",
        "Back it with a bold stat.",
        "Make it a fact that sticks.",
        "Drop a line that’s pure rush.",
        "Reveal a truth that shifts.",
        "Give a stat that’s too good.",
        "Show a find that burns.",
        "Prove it with a fast truth.",
        "Cut it to a gem that roars.",
        "Hand them a fact that lands."
    ]
};

function getRandomPrompt(type) {
    const prompts = creativePrompts[type] || [];
    return prompts[Math.floor(Math.random() * prompts.length)] || "Get creative here!";
}

function generateStructure() {
    const description = document.getElementById('description').value.trim();
    const format = document.getElementById('format').value;
    let output = '';

    if (!description) {
        output = 'Please enter a description!';
    } else {
        switch (format) {
            case 'hook-story-lesson-action':
                output = `- Hook: Grab them with a bold opener\n  *${getRandomPrompt('hook')}*\n` +
                         `- Story: Share your journey\n  *${getRandomPrompt('story')}*\n` +
                         `- Lesson: Reveal the core truth\n  *${getRandomPrompt('lesson')}*\n` +
                         `- Actionable You: Give one clear step\n  *${getRandomPrompt('action')}*`;
                break;
            case 'problem-agitation-solution':
                output = `- Problem: Name the struggle\n  *${getRandomPrompt('problem')}*\n` +
                         `- Agitation: Turn up the heat\n  *${getRandomPrompt('agitation')}*\n` +
                         `- Solution: Deliver the fix\n  *${getRandomPrompt('solution')}*`;
                break;
            case 'question-insight-takeaway':
                output = `- Question: Spark their curiosity\n  *${getRandomPrompt('question')}*\n` +
                         `- Insight: Offer a fresh angle\n  *${getRandomPrompt('insight')}*\n` +
                         `- Takeaway: Leave them with a gem\n  *${getRandomPrompt('takeaway')}*`;
                break;
            case 'listicle':
                output = `- Title: Craft a catchy list headline\n  *${getRandomPrompt('listItem')}*\n` +
                         `- Item 1: Lead with a strong tip\n  *${getRandomPrompt('listItem')}*\n` +
                         `- Item 2: Add a practical idea\n  *${getRandomPrompt('listItem')}*\n` +
                         `- Item 3: Mix in a bold move\n  *${getRandomPrompt('listItem')}*\n` +
                         `- Item 4: Share a hidden gem\n  *${getRandomPrompt('listItem')}*\n` +
                         `- Item 5: End with a bang\n  *${getRandomPrompt('listItem')}*`;
                break;
            case 'myth-fact':
                output = `- Myth: Bust a common lie\n  *${getRandomPrompt('myth')}*\n` +
                         `- Fact: Drop the real deal\n  *${getRandomPrompt('fact')}*`;
                break;
            default:
                output = 'Select a valid format!';
        }
    }

    document.getElementById('output').textContent = output;
}
